name: publish release

on:
  release:
    types:
      - published
        
jobs:
  publish-release:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.2.207
      - name: Install dependencies
        run: dotnet restore
      - name: Build solution
        run: dotnet build --configuration Release --no-restore /p:Version=$GITHUB_REF
      - name: Pack client
        run: dotnet pack  ./client/MAVN.Service.WAMPHost.Client/MAVN.Service.WAMPHost.Client.csproj --configuration Release --no-build --include-symbols --include-source /p:SymbolPackageFormat=snupkg /p:Version=$GITHUB_REF
      - name: Publish client
        env:
          API_KEY: ${{ secrets.NUGET_ORG_API_KEY }}
        run: dotnet nuget push ./client/MAVN.Service.WAMPHost.Client/bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --api-key $API_KEY
      - name: Pack contract
        run: dotnet pack  ./contract/MAVN.Service.WAMPHost.Contract/MAVN.Service.WAMPHost.Contract.csproj --configuration Release --no-build --include-symbols --include-source /p:SymbolPackageFormat=snupkg /p:Version=$GITHUB_REF
      - name: Publish contract
        env:
          API_KEY: ${{ secrets.NUGET_ORG_API_KEY }}
        run: dotnet nuget push ./contract/MAVN.Service.WAMPHost.Contract/bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --api-key $API_KEY