name: publish client

on:
  release:
    types:
      - published
        
jobs:
  pack-and-publish:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.2.207
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build ./client/MAVN.Service.WAMPHost.Client/MAVN.Service.WAMPHost.Client.csproj --configuration Release --no-restore /p:Version=0.0.1
      - name: Pack
        run: dotnet pack ./client/MAVN.Service.WAMPHost.Client/MAVN.Service.WAMPHost.Client.csproj --configuration Release --no-build /p:IncludeSymbols=true /p:SymbolPackageFormat=snupkg /p:Version=0.0.1
      - name: Push
        env:
          API_KEY: ${{ secrets.NUGET_ORG_API_KEY }}
        run: dotnet nuget push ./client/MAVN.Service.WAMPHost.Client/bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --api-key $API_KEY 